name: Docker Container CI

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & Push Image
        run: |
          docker login --username Logan-Garrett --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/logan-garrett/go-dock:latest
          docker push ghcr.io/logan-garrett/go-dock:latest
